# Generated by Django 4.2.16 on 2024-11-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='picked_at',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='placed_at',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
