# Generated by Django 4.2.16 on 2024-11-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_jobhistory_picked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField()),
                ('due', models.DateTimeField()),
                ('pick_at', models.CharField(default='none', max_length=10)),
                ('place_at', models.CharField(default='none', max_length=10)),
                ('estimated_pickup_time', models.DurationField()),
            ],
        ),
    ]
